import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import {LinkArrow} from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>

				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex items-center text-dark w-full min-h-screen'>
				<Layout className='pt-0'>
					<div className='flex Items-center justify-between w-full'>
						<div className='w-1/2'>
							<Image
								priority
								sizes='(max-width: 768px) 100vw,
								(max-width: 1200px) 50vw,
								50vw'
								src={profilePic}
								alt='Andrew'
								className='w-full h-auto'
								draggable='false'
							/>
						</div>
						<div className='w-1/2 flex flex-col items-center self-center'>
							<AnimatedText
								text='Turning Vision Into Reality With Code And Design.'
								className='!text-6xl !text-left dark:text-light'
							/>
							<p className='my-4 text-base font-medium dark:text-light'>
								As a skilled full-stack developer, I am
								dedicated to turning ideas into innovative web
								applications. Explore my latest projects and
								articles, showcasing my expertise in React.js
								and web development.
							</p>
							<div className='flex items-center self-start mt-2'>
								<Link
									href='/dummy.pdf'
									target='_blank'
									className='flex items-center bg-dark dark:bg-light dark:text-dark text-light p-2.5  px-6 rounded-lg text-lg font-semibold hover:bg-light dark:hover:bg-dark hover:text-dark dark:hover:text-white border-2 border-solid border-transparent hover:border-dark dark:hover:border-white'
									download
								>
									Resume
									<LinkArrow className={'w-6 ml-1'} />
								</Link>
								<Link
									href='mailto:androsol.box@gmail.com'
									target='_blank'
									className='ml-4 text-lg font-medium capitalize text-dark dark:text-light underline'
								>
									Contact
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
				<div className='absolute right-8 bottom-8 inline-block w-24'>
					<Image
						src={lightBulb}
						alt='Andrii Soloviov'
						className='w-full h-auto'
					/>
				</div>
			</main>
		</>
	)
}
